fixed cert gen action2

diff --git a/.github/workflows/generate-certificate-list.yml b/.github/workflows/generate-certificate-list.yml
--- a/.github/workflows/generate-certificate-list.yml
+++ b/.github/workflows/generate-certificate-list.yml
@@ -16,8 +16,8 @@ jobs:
 
       - name: Debug directory contents
         run: |
-          ls -R Certificate || echo "Certificate directory not found"
-          find Certificate -maxdepth 1 -type f || echo "No files found in Certificate"
+          ls -R certificates || echo "Certificate directory not found"
+          find certificates -maxdepth 1 -type f || echo "No files found in certificates"
 
       - name: Generate certificateFiles.js
         run: |
